
spring:
  profiles:
    active: default, local
  data:
    mongodb:
      uri: mongodb+srv://kongdev:kongdev21@cluster0.br4nt.mongodb.net/kongdev_db?retryWrites=true&w=majority

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG